config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:edit, :update]
  resources :products
  get '/sign_in', to:'users#sign_in', as: :sign_in
  post '/sign_in', to: 'users#sign_in_process'
  get '/users/new', to:'users#new', as: :new
  post '/users/new', to: 'users#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  validates :describe, presence: true
  validates :price, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format:{ with: VALID_EMAIL_REGEX }
  validates :password, presence: true, length:{minimum: 8}
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include UsersHelper
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] =　'商品を登録しました'
      redirect_to products_path
    else
      flash.now[:danger] = '商品登録に失敗しました'
      redirect_to new_product_path
    end
  end

  def edit
    @product = Product.find(params[:id])
    @product.user_id == current_user.id
  end

  def update
    @product = Product.find(params[:id])
    if @product.save
      flash[:success] =　'商品を編集しました'
      redirect_to products_path
    else
      flash.now[:danger] = '商品を編集できませんでした'
      redirect_to edit_product_path
    end
  end

  def destroy
    @product.destroy
    flash[:success] = "削除しました"
    redirect_to product_index_path
  end

  private
  def product_params
    params.require(:product).permit(:name, :describe, :price).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize, except: [:new, :create, :sign_in, :sign_in_process]

  def new
    @user = User.new
    render layout: "not_login"
  end

  def create
    user = User.new(user_params)
    if user.save
      flash[:success] = 'ユーザー登録しました'
      redirect_to sign_in_path and return
    else
      flash[:danger] = 'ユーザー登録できませんでした'
      redirect_to users_new_path
    end
  end

  def sign_in
    @user = User.new
    render layout: "not_login"
  end

  def sign_in_process
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      user_sign_in(user)
      flash[:success] = 'ログインしました'
      redirect_to products_path
    else
      flash[:danger] = 'ログインに失敗しました'
      redirect_to sign_in_path
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.save
      flash[:success] = '名前を変更しました'
      redirect_to products_path
    else
      flash.now[:danger] = '名前の変更に失敗しました'
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def user_sign_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if @current_user.nil?
       @current_user = User.find_by(id: session[:user_id])
    else
       @current_user
    end
  end

  def user_signed_in?
   current_user.present?
  end

  def authorize
   redirect_to sign_in_path unless user_signed_in?
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="global_header">
    <%= link_to 'SHOP', products_path %>
    <%= link_to '商品登録', new_product_path %>
    <%= link_to 'プロフィール編集',edit_user_path(@user.id) %>
  </header>
    <%= yield %>
    <% flash.each do |message_type, message| %>
      <%= message %>
    <% end %>
  </body>
</html>

app/views/layouts/not_login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <% flash.each do |message_type, message| %>
      <%= message %>
    <% end %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for (@product) do |form| %>
  <div class="field">
    <%= form.label :"名前" %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :"説明" %>
    <%= form.text_field :describe %>
  </div>

  <div class="field">
    <%= form.label :"金額" %>
    <%= form.text_field :price %>
  </div>

  <div class="actions">
    <%= form.submit "商品登録" %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h3>商品編集</h3>

<%= render 'form', product: @product %>

app/views/products/index.html.erb
<h3>商品一覧</h3>
<% if @products.any? %>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.text %></td>
      <td><%= product.price %></td>
      <td><%= user.id %></td>
      <% if @product.user_id == current_user.id %>
        <%= link_to '編集する', edit_product_path(@product.id) %>
          <%= link_to product_path(@product), method: :delete do %>
            <p>削除する</p>
          <% end %>
      <% end %>
    </tr>
  <% end %>
<% else %>
  <p class= "empty">商品はありません</p>
<% end %>

app/views/products/new.html.erb
<h3>商品登録</h3>

<%= render 'form', product: @product %>

app/views/users/edit.html.erb
<h3>プロフィール編集</h3>
  <%= form_for (@user) do |form| %>
    <div class="field">
      <%= form.label :"名前" %>
      <%= form.text_field :name %>
    </div>

    <div class="actions">
      <%= form.submit "登録" %>
    </div>
  <% end %>

app/views/users/new.html.erb
<h3>ユーザー登録</h3>
  <%= form_for @user, url: users_new_path do |f| %>
     <div class="field">
       <%= f.email_field :email, placeholder: "メールアドレス" %>
     </div>
     <div class="field">
       <%= f.password_field :password, placeholder: "パスワード" %>
     </div>
     <div class="actions">
       <%= f.submit "登録" %>
     </div>
   <% end %>

  <div class="login_link">
    <p>アカウントをお持ちですか？ <%= link_to 'ログインする',sign_in_path %></p>
  </div>

app/views/users/sign_in.html.erb
<h3>ログイン</h3>
  <%= form_for @user, url: sign_in_path do |f| %>
    <div class="field">
      <%= f.email_field :email, placeholder: "メールアドレス" %>
    </div>
    <div class="field">
      <%= f.password_field :password, placeholder: "パスワード" %>
    </div>
    <div class="actions">
      <%= f.submit "ログイン" %>
    </div>
  <% end %>

  <div class="sign_in_link">
    <p>アカウントをお持ちですか？ <%= link_to users_new_path do %>新規登録する<% end %></p>
  </div>